### ISSUE TITLE
Manager User

### ISSUE THREAD

**Issue by XPPP2** [XPPP2/AppointHospital#2]
### Epic
Allow manager user to login and check and manage the data in their page. 
In manager account, they can see the status of each appointment and information of users.
Manager should have the ability to manage Member user accounts and hospital information. 
Moreover, managers can add or delete the label for customers to search for hospital. Manager could approve new enrollment.
In Manager's page, there will also be a statistic system to show recent appointment data.

### Stories

- [x] Manager Login:[ Manager: Manager Login](https://github.com/XPPP2/AppointHospital/issues/4)
- [x] Manage Member User Account: [Manager:Manage Member User Account](https://github.com/XPPP2/AppointHospital/issues/6)
- [x] Check Appointment History List: [Manager: Check Appointment History List](https://github.com/XPPP2/AppointHospital/issues/10)
- [x] Manage Doctor Information: [Manager: Manage Doctor Information](https://github.com/XPPP2/AppointHospital/issues/7)
- [x] Check Statistic Information: [Manager: Check Statistic Information](https://github.com/XPPP2/AppointHospital/issues/1)
- [x] Manager:Manage Department: [Manage Department](https://github.com/XPPP2/AppointHospital/issues/12)
