### ISSUE TITLE
Member User

### ISSUE THREAD

**Issue by XPPP2** [XPPP2/AppointHospital#3]
### Epic
By using phone number, members can login to the app. Member users can fill in the form and apply for Absence Request. 
Members should see the list of their own applying. Members also have a list of applying waiting for their approval. Members can have a history of the applying they approved.

### Stories

- [x] Member User Login : [Member User: Member user Login](https://github.com/XPPP2/AppointHospital/issues/5)
- [x] Check Doctor Information : [Member User: Check Doctor Information](https://github.com/XPPP2/AppointHospital/issues/8)
- [x] Making Appointment  : [Member User: Making Appointment ](https://github.com/XPPP2/AppointHospital/issues/9)
- [x] View Personal Information : [Member User: View Personal Information](https://github.com/XPPP2/AppointHospital/issues/11)
